config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :users
  resources :quizzes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, :last_name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  def new
    @quiz = Question.all.limit(5).order("RANDOM()")
  end

  def create
    @name = [Faker::Superhero.prefix, Faker::Superhero.name].join(' ')
    @power = Faker::Superhero.power
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_quiz_path
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :subscription)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>SUPER HERO QUIZ</h1>

<p>Generate your super hero name and powers with this fun, interactive quiz!</p>

<div class="container">
  <div class="row justify-content-center">
    <%= link_to 'GET STARTED', new_user_path, class: 'btn btn-lg btn-danger' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperHeroQuiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quizzes/create.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h1>WE'VE FOUND YOUR SUPERHERO NAME</h1>

    <h2>Congratulations <%= @name %> with the power of <%= @power %></h2>
  </div>

  <div class="row justify-content-center">
    <%= link_to 'Take quiz again', new_quiz_path, class: 'btn btn-lg btn-danger' %>   
  </div>
</div>

app/views/quizzes/new.html.erb
<div class="container quiz-form">
  <h1>Questions</h1>
  <div class="row justify-content-center">
    <%= form_tag quizzes_path do %>
      <% @quiz.each.with_index do |question, i| %>
        <div class="form-group">
          <label><%= question.inquiry %></label>
          <% %i{answer_1 answer_2 answer_3 answer_4}.each do |field| %>
            <div class="form-check">
              <%= radio_button_tag "answer-#{i}", question.send(field), class: 'form-check-input' %>
              <%= label_tag "answer-#{i}", question.send(field), class: 'form-check-label' %>
            </div>
          <% end %>
        </div>
      <% end %>
      <%= submit_tag "Submit", class: 'btn btn-info' %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Enter your information</h1>
  <% if @user.errors.present? %>
    <% @user.errors.full_messages.each do |error|  %>
      <%= error %>
    <% end %>
  <% end %>
  <%= form_with model: @user, local: true do |f| %>

    <div class="form-group">
      <%= f.label :first_name, 'First Name' %>
      <%= f.text_field :first_name, class: 'form-control', placeholder: 'First Name' %>
    </div>

    <div class="form-group">
      <%= f.label :last_name, 'Last Name' %>
      <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last Name' %>
    </div>

    <div class="form-group">
      <%= f.label :email, 'Email' %>
      <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
    </div>

    <div class="form-group form-check">
      <%= f.check_box(:subscription, checked: true, class: 'form-check-input') %>
      <%= f.label :subscription, 'Sign Me Up!', class: 'form-check-label' %>
    </div>

    <%= f.submit 'Submit', class: 'btn btn-info' %>

  <% end %>
</div>